In [175]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [176]:
df = pd.read_csv("/content/train.csv")

In [177]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [178]:
df[df['toxic'] == 1].head()

id                                       comment_text  \
6   0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
12  0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......   
16  0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...   
42  001810bf8c45bf5f  You are gay or antisemmitian? \n\nArchangel WH...   
43  00190820581d90ce           FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!   

    toxic  severe_toxic  obscene  threat  insult  identity_hate  
6       1             1        1       0       1              0  
12      1             0        0       0       0              0  
16      1             0        0       0       0              0  
42      1             0        1       0       1              1  
43      1             0        1       0       1              0

In [179]:
df.iloc[7]['comment_text']

"Your vandalism to the Matt Shirvington article has been reverted.  Please don't do it again, or you will be banned."

In [180]:
df[df.columns[2:]].iloc[5]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 5, dtype: int64

In [181]:
from tensorflow.keras.layers import TextVectorization

In [182]:
df = df.head(5000)

In [183]:
X = df['comment_text']
y = df[df.columns[2:]].values

In [184]:
X

0       Explanation\nWhy the edits made under my usern...
1       D'aww! He matches this background colour I'm s...
2       Hey man, I'm really not trying to edit war. It...
3       "\nMore\nI can't make any real suggestions on ...
4       You, sir, are my hero. Any chance you remember...
                              ...                        
4995    "\n\nHello Marcruhwedell, and Welcome to Wikip...
4996    ...that's why I did ....cheers,   (talk · cont...
4997    No, it's not a delayed reaction\n\nI just happ...
4998    "\n\nA slight difference with you\nI have to d...
4999    "\n\nNonsense.  The truth is NO schools give s...
Name: comment_text, Length: 5000, dtype: object

In [185]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [186]:
#Max_features
voc_size = 10000

In [187]:
vectorizer = TextVectorization(max_tokens=voc_size,output_sequence_length = 1800,output_mode = "int")


In [188]:
X.values

array(["Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27",
       "D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)",
       "Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info.",
       ...,
       "No, it's not a delayed reaction\n\nI just happened to read your wonderful warning yesterday. Unlike you, I don't visit Wikipedia everyday. But I'm surprised to see that you are too dense to figure that out.\n\nIdiot. HA HA HA HA HA XD",
       '"\n\nA slight difference with you\nI have to disagree with your comment above that some of B

In [189]:
vectorizer.adapt(X.values)

In [190]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'i',
 'a',
 'and',
 'you',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'with',
 'your',
 'if',
 'was',
 'article',
 'or',
 'but',
 'page',
 'an',
 'my',
 'by',
 'from',
 'do',
 'at',
 'me',
 'about',
 'so',
 'what',
 'wikipedia',
 'can',
 'there',
 'has',
 'all',
 'would',
 'like',
 'its',
 'will',
 'no',
 'talk',
 'one',
 'just',
 'any',
 'please',
 'they',
 'he',
 'been',
 'which',
 'we',
 'dont',
 'here',
 'other',
 'ass',
 'should',
 'more',
 'see',
 'his',
 'some',
 'who',
 'im',
 'also',
 'think',
 'know',
 'how',
 'because',
 'out',
 'why',
 'then',
 'am',
 'edit',
 'were',
 'only',
 'use',
 'people',
 'up',
 'articles',
 'may',
 'now',
 'time',
 'being',
 'did',
 'their',
 'when',
 'than',
 'thanks',
 'get',
 'information',
 'even',
 'make',
 'good',
 'them',
 'sources',
 'well',
 'had',
 'could',
 'want',
 'deletion',
 'way',
 'very',
 'fuck',
 'first',
 'does',
 'name',
 'really',
 'made',

In [191]:
vectorized_text = vectorizer(X.values)

In [192]:
vectorized_text

<tf.Tensor: shape=(5000, 1800), dtype=int64, numpy=
array([[ 602,   76,    2, ...,    0,    0,    0],
       [   1,   55, 1825, ...,    0,    0,    0],
       [ 504,  412,   69, ...,    0,    0,    0],
       ...,
       [  48,   46,   15, ...,    0,    0,    0],
       [   6, 5215,  878, ...,    0,    0,    0],
       [ 742,    2,  559, ...,    0,    0,    0]])>

In [193]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)

In [194]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [195]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [196]:
model = Sequential()
model.add(Embedding(voc_size+1, 32))
model.add(Bidirectional(LSTM(32, activation='tanh')))
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(6, activation='sigmoid'))

In [197]:
model.compile(loss='BinaryCrossentropy', optimizer='Adam')

In [198]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, None, 32)          320032    
                                                                 
 bidirectional_5 (Bidirecti  (None, 64)                16640     
 onal)                                                           
                                                                 
 dense_20 (Dense)            (None, 128)               8320      
                                                                 
 dense_21 (Dense)            (None, 256)               33024     
                                                                 
 dense_22 (Dense)            (None, 128)               32896     
                                                                 
 dense_23 (Dense)            (None, 6)                 774       
                                                      

In [ ]:
history = model.fit(train, epochs=1, validation_data=val)

182/219 [=======================>......] - ETA: 1:05 - loss: 0.1880

In [ ]:
input_text = vectorizer('You freaking suck! I am going to kill you.')

In [ ]:
np.expand_dims(input_text,0)

In [ ]:
model.predict(np.expand_dims(input_text,0))


In [ ]:
(res > 0.5).astype(int)

In [ ]:
batch_X, batch_y = test.as_numpy_iterator().next()

In [ ]:
(model.predict(batch_X) > 0.5).astype(int)

In [ ]:
res.shape

In [ ]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [ ]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [ ]:
for batch in test.as_numpy_iterator():
    # Unpack the batch
    X_true, y_true = batch
    # Make a prediction
    yhat = model.predict(X_true)

    # Flatten the predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()

    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

In [ ]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')